-- Active: 1787232778471@@dpg-da3ffkbtqb8s73cpm70g-a.frankfurt-postgres.render.com@5432@thesis_db_koxh
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: delete_dialogue_after_reel_delete(); Type: FUNCTION; Schema: public; Owner: root
--

CREATE FUNCTION public.delete_dialogue_after_reel_delete() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  IF OLD.dialogue_id IS NOT NULL THEN
    DELETE FROM public.dialogues WHERE id = OLD.dialogue_id;
  END IF;
  RETURN OLD;
END;
$$;


ALTER FUNCTION public.delete_dialogue_after_reel_delete() OWNER TO thesis_db_koxh_user;

--
-- Name: FUNCTION delete_dialogue_after_reel_delete(); Type: COMMENT; Schema: public; Owner: root
--

COMMENT ON FUNCTION public.delete_dialogue_after_reel_delete() IS 'Deletes a reel''s dialogue (and transitively its dialogue_sentences) after the reel is deleted';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: dialogue_sentences; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.dialogue_sentences (
    id bigint NOT NULL,
    dialogue_id bigint NOT NULL,
    sentence_id bigint NOT NULL,
    "position" smallint NOT NULL,
    start_time_ms integer,
    end_time_ms integer,
    CONSTRAINT valid_time CHECK ((((start_time_ms IS NULL) AND (end_time_ms IS NULL)) OR (end_time_ms > start_time_ms)))
);


ALTER TABLE public.dialogue_sentences OWNER TO thesis_db_koxh_user;

--
-- Name: dialogue_sentences_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.dialogue_sentences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.dialogue_sentences_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: dialogue_sentences_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.dialogue_sentences_id_seq OWNED BY public.dialogue_sentences.id;


--
-- Name: dialogues; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.dialogues (
    id bigint NOT NULL,
    language_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    sentences_json jsonb
);


ALTER TABLE public.dialogues OWNER TO thesis_db_koxh_user;

--
-- Name: dialogues_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.dialogues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.dialogues_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: dialogues_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.dialogues_id_seq OWNED BY public.dialogues.id;


--
-- Name: email_verification_codes; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.email_verification_codes (
    email character varying(255) NOT NULL,
    code_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.email_verification_codes OWNER TO thesis_db_koxh_user;

--
-- Name: feedback; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.feedback (
    id bigint NOT NULL,
    category text NOT NULL,
    message text NOT NULL,
    email character varying(255) NOT NULL,
    user_agent text,
    ip_address text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT feedback_category_check CHECK ((category = ANY (ARRAY['bug'::text, 'suggestion'::text, 'question'::text, 'account_access'::text, 'other'::text]))),
    CONSTRAINT feedback_email_not_blank CHECK ((length(btrim((email)::text)) > 0)),
    CONSTRAINT feedback_message_not_blank CHECK ((length(btrim(message)) > 0))
);


ALTER TABLE public.feedback OWNER TO thesis_db_koxh_user;

--
-- Name: TABLE feedback; Type: COMMENT; Schema: public; Owner: root
--

COMMENT ON TABLE public.feedback IS 'Feedback submitted via the public feedback page (backend/public/feedback.html), no account required.';


--
-- Name: feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: languages; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.languages (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(10) NOT NULL
);


ALTER TABLE public.languages OWNER TO thesis_db_koxh_user;

--
-- Name: languages_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.languages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.languages_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: languages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.languages_id_seq OWNED BY public.languages.id;


--
-- Name: letters; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.letters (
    id bigint NOT NULL,
    writing_style character varying(100),
    letter_sign character varying(10) NOT NULL,
    type character varying(9) NOT NULL,
    audio_url text,
    image_url text,
    language_id bigint NOT NULL,
    CONSTRAINT letters_type_check CHECK (((type)::text = ANY (ARRAY['vowel'::text, 'consonant'::text])))
);


ALTER TABLE public.letters OWNER TO thesis_db_koxh_user;

--
-- Name: letters_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.letters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.letters_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: letters_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.letters_id_seq OWNED BY public.letters.id;


--
-- Name: password_reset_codes; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.password_reset_codes (
    email character varying(255) NOT NULL,
    code_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.password_reset_codes OWNER TO thesis_db_koxh_user;

--
-- Name: reel_interactions; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.reel_interactions (
    id bigint NOT NULL,
    reel_id bigint NOT NULL,
    user_id bigint NOT NULL,
    viewed_at timestamp with time zone DEFAULT now() NOT NULL,
    is_liked boolean DEFAULT false NOT NULL,
    is_saved boolean DEFAULT false NOT NULL,
    comment text,
    commented_at timestamp with time zone,
    is_shared boolean DEFAULT false NOT NULL
);


ALTER TABLE public.reel_interactions OWNER TO thesis_db_koxh_user;

--
-- Name: reel_interactions_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.reel_interactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.reel_interactions_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: reel_interactions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.reel_interactions_id_seq OWNED BY public.reel_interactions.id;


--
-- Name: reel_reports; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.reel_reports (
    id bigint NOT NULL,
    reel_id bigint NOT NULL,
    user_id bigint NOT NULL,
    reason text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.reel_reports OWNER TO thesis_db_koxh_user;

--
-- Name: reel_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.reel_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.reel_reports_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: reel_reports_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.reel_reports_id_seq OWNED BY public.reel_reports.id;


--
-- Name: reels; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.reels (
    id bigint NOT NULL,
    language_id integer,
    dialogue_id bigint,
    created_by bigint,
    url text NOT NULL,
    thumbnail_url text,
    title text,
    duration smallint,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.reels OWNER TO thesis_db_koxh_user;

--
-- Name: reels_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.reels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.reels_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: reels_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.reels_id_seq OWNED BY public.reels.id;


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    family_id uuid DEFAULT gen_random_uuid() NOT NULL,
    token_hash text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    replaced_by_id bigint,
    user_agent text,
    ip_address text,
    last_used_at timestamp with time zone
);


ALTER TABLE public.refresh_tokens OWNER TO thesis_db_koxh_user;

--
-- Name: TABLE refresh_tokens; Type: COMMENT; Schema: public; Owner: root
--

COMMENT ON TABLE public.refresh_tokens IS 'Refresh token sessions. One row per issued token; rotation chains rows via family_id. expires_at is fixed at family creation (absolute cap) and copied forward on rotation.';


--
-- Name: COLUMN refresh_tokens.family_id; Type: COMMENT; Schema: public; Owner: root
--

COMMENT ON COLUMN public.refresh_tokens.family_id IS 'Shared by every token in a rotation chain from one login. Revoking a family revokes the whole chain (reuse detection / logout).';


--
-- Name: COLUMN refresh_tokens.expires_at; Type: COMMENT; Schema: public; Owner: root
--

COMMENT ON COLUMN public.refresh_tokens.expires_at IS 'Absolute cap set once at family creation; unchanged by rotation.';


--
-- Name: COLUMN refresh_tokens.revoked_at; Type: COMMENT; Schema: public; Owner: root
--

COMMENT ON COLUMN public.refresh_tokens.revoked_at IS 'NULL = active. Set on rotation (old row), reuse detection, logout, or password reset.';


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sentence_tokens; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.sentence_tokens (
    id bigint NOT NULL,
    sentence_id bigint NOT NULL,
    word_id integer NOT NULL,
    "position" smallint NOT NULL,
    part_of_speech character varying(10),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.sentence_tokens OWNER TO thesis_db_koxh_user;

--
-- Name: sentence_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.sentence_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.sentence_tokens_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: sentence_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.sentence_tokens_id_seq OWNED BY public.sentence_tokens.id;


--
-- Name: sentence_translations; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.sentence_translations (
    id bigint NOT NULL,
    sentence_id bigint NOT NULL,
    translation_sentence_id bigint NOT NULL
);


ALTER TABLE public.sentence_translations OWNER TO thesis_db_koxh_user;

--
-- Name: sentence_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.sentence_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.sentence_translations_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: sentence_translations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.sentence_translations_id_seq OWNED BY public.sentence_translations.id;


--
-- Name: sentences; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.sentences (
    id bigint NOT NULL,
    language_id integer NOT NULL,
    text text NOT NULL,
    normalized_text text,
    audio_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.sentences OWNER TO thesis_db_koxh_user;

--
-- Name: sentences_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.sentences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.sentences_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: sentences_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.sentences_id_seq OWNED BY public.sentences.id;


--
-- Name: word_translations; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.word_translations (
    id bigint NOT NULL,
    word_id bigint NOT NULL,
    translation_word_id bigint NOT NULL,
    level character varying(2),
    CONSTRAINT translations_check CHECK ((word_id <> translation_word_id))
);


ALTER TABLE public.word_translations OWNER TO thesis_db_koxh_user;

--
-- Name: translations_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.translations_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: translations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.translations_id_seq OWNED BY public.word_translations.id;


--
-- Name: user_languages; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.user_languages (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    native_language_id bigint NOT NULL,
    learning_language_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    proficiency_level character varying(50) DEFAULT 'A1'::character varying NOT NULL,
    experience integer DEFAULT 0 NOT NULL,
    is_current_language boolean DEFAULT false
);


ALTER TABLE public.user_languages OWNER TO thesis_db_koxh_user;

--
-- Name: user_languages_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.user_languages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_languages_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: user_languages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.user_languages_id_seq OWNED BY public.user_languages.id;


--
-- Name: user_sentences; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.user_sentences (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    sentence_id bigint NOT NULL,
    user_languages_id bigint NOT NULL,
    mastery_level smallint DEFAULT 1 NOT NULL,
    last_review timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    review_count integer DEFAULT 0 NOT NULL,
    next_review_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT user_sentences_mastery_level_check CHECK (((mastery_level >= 1) AND (mastery_level <= 6)))
);


ALTER TABLE public.user_sentences OWNER TO thesis_db_koxh_user;

--
-- Name: TABLE user_sentences; Type: COMMENT; Schema: public; Owner: root
--

COMMENT ON TABLE public.user_sentences IS 'Per-user saved sentences with mastery/review tracking, mirroring user_vocabulary. Populated only by explicit user action - no proficiency-based auto-seed, since sentences has no level column.';


--
-- Name: user_sentences_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.user_sentences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_sentences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_vocabulary; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.user_vocabulary (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    word_id bigint NOT NULL,
    mastery_level smallint DEFAULT 1 NOT NULL,
    last_review timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_languages_id bigint NOT NULL,
    review_count integer DEFAULT 0 NOT NULL,
    next_review_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT user_vocabulary_mastery_level_check CHECK (((mastery_level >= 1) AND (mastery_level <= 6)))
);


ALTER TABLE public.user_vocabulary OWNER TO thesis_db_koxh_user;

--
-- Name: user_vocabulary_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.user_vocabulary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_vocabulary_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: user_vocabulary_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.user_vocabulary_id_seq OWNED BY public.user_vocabulary.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    google_id text,
    first_name character varying(100),
    last_name character varying(100),
    username character varying(50) NOT NULL,
    password_hash text,
    email character varying(255),
    profile_picture text,
    joined_date timestamp with time zone DEFAULT now() NOT NULL,
    last_login timestamp with time zone,
    energy integer DEFAULT 100 NOT NULL,
    coins integer DEFAULT 0 NOT NULL,
    age integer,
    preferences character varying(100),
    notifications boolean DEFAULT true,
    email_verified boolean DEFAULT false,
    coins_updated_at timestamp with time zone DEFAULT now() NOT NULL,
    energy_updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT users_age_check CHECK (((age >= 0) AND (age <= 100))),
    CONSTRAINT users_coins_check CHECK ((coins >= 0)),
    CONSTRAINT users_energy_check CHECK ((energy >= 0))
);


ALTER TABLE public.users OWNER TO thesis_db_koxh_user;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: grammer_videos; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.grammer_videos (
    id bigint NOT NULL,
    youtube_url text NOT NULL,
    title text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    learning_language_id bigint NOT NULL
);


ALTER TABLE public.grammer_videos OWNER TO thesis_db_koxh_user;

--
-- Name: grammer_videos_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.grammer_videos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grammer_videos_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: grammer_videos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.grammer_videos_id_seq OWNED BY public.grammer_videos.id;


--
-- Name: words; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.words (
    id bigint NOT NULL,
    written_form character varying(255) NOT NULL,
    part_of_speech character varying(50),
    image_url text,
    audio_url text,
    language_id bigint NOT NULL,
    level character varying(2),
    article character varying(10),
    normalized_text text,
    CONSTRAINT words_level_check CHECK (((level)::text = ANY (ARRAY['N'::text, 'A1'::text, 'A2'::text, 'B1'::text, 'B2'::text, 'AB'::text, 'C1'::text, 'C2'::text, 'EX'::text])))
);


ALTER TABLE public.words OWNER TO thesis_db_koxh_user;

--
-- Name: words_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.words_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.words_id_seq OWNER TO thesis_db_koxh_user;

--
-- Name: words_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.words_id_seq OWNED BY public.words.id;


--
-- Name: dialogue_sentences id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.dialogue_sentences ALTER COLUMN id SET DEFAULT nextval('public.dialogue_sentences_id_seq'::regclass);


--
-- Name: dialogues id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.dialogues ALTER COLUMN id SET DEFAULT nextval('public.dialogues_id_seq'::regclass);


--
-- Name: languages id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.languages ALTER COLUMN id SET DEFAULT nextval('public.languages_id_seq'::regclass);


--
-- Name: letters id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.letters ALTER COLUMN id SET DEFAULT nextval('public.letters_id_seq'::regclass);


--
-- Name: reel_interactions id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reel_interactions ALTER COLUMN id SET DEFAULT nextval('public.reel_interactions_id_seq'::regclass);


--
-- Name: reel_reports id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reel_reports ALTER COLUMN id SET DEFAULT nextval('public.reel_reports_id_seq'::regclass);


--
-- Name: reels id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reels ALTER COLUMN id SET DEFAULT nextval('public.reels_id_seq'::regclass);


--
-- Name: sentence_tokens id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.sentence_tokens ALTER COLUMN id SET DEFAULT nextval('public.sentence_tokens_id_seq'::regclass);


--
-- Name: sentence_translations id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.sentence_translations ALTER COLUMN id SET DEFAULT nextval('public.sentence_translations_id_seq'::regclass);


--
-- Name: sentences id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.sentences ALTER COLUMN id SET DEFAULT nextval('public.sentences_id_seq'::regclass);


--
-- Name: user_languages id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_languages ALTER COLUMN id SET DEFAULT nextval('public.user_languages_id_seq'::regclass);


--
-- Name: user_vocabulary id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_vocabulary ALTER COLUMN id SET DEFAULT nextval('public.user_vocabulary_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: grammer_videos id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.grammer_videos ALTER COLUMN id SET DEFAULT nextval('public.grammer_videos_id_seq'::regclass);


--
-- Name: word_translations id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.word_translations ALTER COLUMN id SET DEFAULT nextval('public.translations_id_seq'::regclass);


--
-- Name: words id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.words ALTER COLUMN id SET DEFAULT nextval('public.words_id_seq'::regclass);


--
-- Name: dialogue_sentences dialogue_sentences_dialogue_id_position_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.dialogue_sentences
    ADD CONSTRAINT dialogue_sentences_dialogue_id_position_key UNIQUE (dialogue_id, "position");


--
-- Name: dialogue_sentences dialogue_sentences_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.dialogue_sentences
    ADD CONSTRAINT dialogue_sentences_pkey PRIMARY KEY (id);


--
-- Name: dialogues dialogues_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.dialogues
    ADD CONSTRAINT dialogues_pkey PRIMARY KEY (id);


--
-- Name: email_verification_codes email_verification_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.email_verification_codes
    ADD CONSTRAINT email_verification_codes_pkey PRIMARY KEY (email);


--
-- Name: feedback feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);


--
-- Name: languages languages_code_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT languages_code_key UNIQUE (code);


--
-- Name: languages languages_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT languages_pkey PRIMARY KEY (id);


--
-- Name: letters letters_letter_sign_language_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.letters
    ADD CONSTRAINT letters_letter_sign_language_id_key UNIQUE (letter_sign, language_id);


--
-- Name: letters letters_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.letters
    ADD CONSTRAINT letters_pkey PRIMARY KEY (id);


--
-- Name: password_reset_codes password_reset_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.password_reset_codes
    ADD CONSTRAINT password_reset_codes_pkey PRIMARY KEY (email);


--
-- Name: reel_interactions reel_interactions_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reel_interactions
    ADD CONSTRAINT reel_interactions_pkey PRIMARY KEY (id);


--
-- Name: reel_interactions reel_interactions_reel_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reel_interactions
    ADD CONSTRAINT reel_interactions_reel_id_user_id_key UNIQUE (reel_id, user_id);


--
-- Name: reel_reports reel_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reel_reports
    ADD CONSTRAINT reel_reports_pkey PRIMARY KEY (id);


--
-- Name: reel_reports reel_reports_reel_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reel_reports
    ADD CONSTRAINT reel_reports_reel_id_user_id_key UNIQUE (reel_id, user_id);


--
-- Name: reels reels_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reels
    ADD CONSTRAINT reels_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash);


--
-- Name: sentence_tokens sentence_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.sentence_tokens
    ADD CONSTRAINT sentence_tokens_pkey PRIMARY KEY (id);


--
-- Name: sentence_tokens sentence_tokens_sentence_id_position_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.sentence_tokens
    ADD CONSTRAINT sentence_tokens_sentence_id_position_key UNIQUE (sentence_id, "position");


--
-- Name: sentence_translations sentence_translations_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.sentence_translations
    ADD CONSTRAINT sentence_translations_pkey PRIMARY KEY (id);


--
-- Name: sentence_translations sentence_translations_sentence_id_translation_sentence_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.sentence_translations
    ADD CONSTRAINT sentence_translations_sentence_id_translation_sentence_id_key UNIQUE (sentence_id, translation_sentence_id);


--
-- Name: sentences sentences_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.sentences
    ADD CONSTRAINT sentences_pkey PRIMARY KEY (id);


--
-- Name: word_translations translations_from_word_id_to_word_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.word_translations
    ADD CONSTRAINT translations_from_word_id_to_word_id_key UNIQUE (word_id, translation_word_id);


--
-- Name: word_translations translations_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.word_translations
    ADD CONSTRAINT translations_pkey PRIMARY KEY (id);


--
-- Name: user_languages user_languages_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_languages
    ADD CONSTRAINT user_languages_pkey PRIMARY KEY (id);


--
-- Name: user_sentences user_sentences_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_sentences
    ADD CONSTRAINT user_sentences_pkey PRIMARY KEY (id);


--
-- Name: user_vocabulary user_vocabulary_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_vocabulary
    ADD CONSTRAINT user_vocabulary_pkey PRIMARY KEY (id);


--
-- Name: user_vocabulary user_vocabulary_user_word_lang_unique; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_vocabulary
    ADD CONSTRAINT user_vocabulary_user_word_lang_unique UNIQUE (user_id, word_id, user_languages_id);


--
-- Name: users users_google_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_google_id_key UNIQUE (google_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: grammer_videos grammer_videos_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.grammer_videos
    ADD CONSTRAINT grammer_videos_pkey PRIMARY KEY (id);


--
-- Name: grammer_videos grammer_videos_youtube_url_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.grammer_videos
    ADD CONSTRAINT grammer_videos_youtube_url_key UNIQUE (youtube_url);


--
-- Name: words words_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.words
    ADD CONSTRAINT words_pkey PRIMARY KEY (id);


--
-- Name: idx_feedback_created_at; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_feedback_created_at ON public.feedback USING btree (created_at DESC);


--
-- Name: idx_refresh_tokens_family_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_refresh_tokens_family_id ON public.refresh_tokens USING btree (family_id);


--
-- Name: idx_refresh_tokens_user_active; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_refresh_tokens_user_active ON public.refresh_tokens USING btree (user_id) WHERE (revoked_at IS NULL);


--
-- Name: idx_user_sentences_user_lang; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_user_sentences_user_lang ON public.user_sentences USING btree (user_id, user_languages_id);


--
-- Name: idx_words_language_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_words_language_id ON public.words USING btree (language_id);


--
-- Name: uq_user_sentences_user_sentence; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX uq_user_sentences_user_sentence ON public.user_sentences USING btree (user_id, sentence_id);


--
-- Name: users_email_unique_idx; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX users_email_unique_idx ON public.users USING btree (email) WHERE (email IS NOT NULL);


--
-- Name: reels trigger_delete_dialogue_after_reel_delete; Type: TRIGGER; Schema: public; Owner: root
--

CREATE TRIGGER trigger_delete_dialogue_after_reel_delete AFTER DELETE ON public.reels FOR EACH ROW EXECUTE FUNCTION public.delete_dialogue_after_reel_delete();


--
-- Name: TRIGGER trigger_delete_dialogue_after_reel_delete ON reels; Type: COMMENT; Schema: public; Owner: root
--

COMMENT ON TRIGGER trigger_delete_dialogue_after_reel_delete ON public.reels IS 'Deletes the associated dialogue whenever a reel row is deleted';


--
-- Name: dialogue_sentences dialogue_sentences_dialogue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.dialogue_sentences
    ADD CONSTRAINT dialogue_sentences_dialogue_id_fkey FOREIGN KEY (dialogue_id) REFERENCES public.dialogues(id) ON DELETE CASCADE;


--
-- Name: dialogue_sentences dialogue_sentences_sentence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.dialogue_sentences
    ADD CONSTRAINT dialogue_sentences_sentence_id_fkey FOREIGN KEY (sentence_id) REFERENCES public.sentences(id);


--
-- Name: dialogues dialogues_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.dialogues
    ADD CONSTRAINT dialogues_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.languages(id);


--
-- Name: user_sentences fk_user_sentences_user_languages; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_sentences
    ADD CONSTRAINT fk_user_sentences_user_languages FOREIGN KEY (user_languages_id) REFERENCES public.user_languages(id) ON DELETE CASCADE;


--
-- Name: user_vocabulary fk_user_vocabulary_user_languages; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_vocabulary
    ADD CONSTRAINT fk_user_vocabulary_user_languages FOREIGN KEY (user_languages_id) REFERENCES public.user_languages(id) ON DELETE CASCADE;


--
-- Name: letters letters_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.letters
    ADD CONSTRAINT letters_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.languages(id) ON DELETE CASCADE;


--
-- Name: grammer_videos grammer_videos_learning_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.grammer_videos
    ADD CONSTRAINT grammer_videos_learning_language_id_fkey FOREIGN KEY (learning_language_id) REFERENCES public.languages(id) ON DELETE CASCADE;


--
-- Name: reel_interactions reel_interactions_reel_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reel_interactions
    ADD CONSTRAINT reel_interactions_reel_id_fkey FOREIGN KEY (reel_id) REFERENCES public.reels(id) ON DELETE CASCADE;


--
-- Name: reel_interactions reel_interactions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reel_interactions
    ADD CONSTRAINT reel_interactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: reel_reports reel_reports_reel_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reel_reports
    ADD CONSTRAINT reel_reports_reel_id_fkey FOREIGN KEY (reel_id) REFERENCES public.reels(id) ON DELETE CASCADE;


--
-- Name: reel_reports reel_reports_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reel_reports
    ADD CONSTRAINT reel_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: reels reels_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reels
    ADD CONSTRAINT reels_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: reels reels_dialogue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reels
    ADD CONSTRAINT reels_dialogue_id_fkey FOREIGN KEY (dialogue_id) REFERENCES public.dialogues(id) ON DELETE SET NULL;


--
-- Name: reels reels_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.reels
    ADD CONSTRAINT reels_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.languages(id);


--
-- Name: refresh_tokens refresh_tokens_replaced_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_replaced_by_id_fkey FOREIGN KEY (replaced_by_id) REFERENCES public.refresh_tokens(id) ON DELETE SET NULL;


--
-- Name: refresh_tokens refresh_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: sentence_tokens sentence_tokens_sentence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.sentence_tokens
    ADD CONSTRAINT sentence_tokens_sentence_id_fkey FOREIGN KEY (sentence_id) REFERENCES public.sentences(id) ON DELETE CASCADE;


--
-- Name: sentence_tokens sentence_tokens_word_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.sentence_tokens
    ADD CONSTRAINT sentence_tokens_word_id_fkey FOREIGN KEY (word_id) REFERENCES public.words(id);


--
-- Name: sentence_translations sentence_translations_sentence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.sentence_translations
    ADD CONSTRAINT sentence_translations_sentence_id_fkey FOREIGN KEY (sentence_id) REFERENCES public.sentences(id) ON DELETE CASCADE;


--
-- Name: sentence_translations sentence_translations_translation_sentence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.sentence_translations
    ADD CONSTRAINT sentence_translations_translation_sentence_id_fkey FOREIGN KEY (translation_sentence_id) REFERENCES public.sentences(id) ON DELETE CASCADE;


--
-- Name: sentences sentences_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.sentences
    ADD CONSTRAINT sentences_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.languages(id);


--
-- Name: word_translations translations_translation_word_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.word_translations
    ADD CONSTRAINT translations_translation_word_id_fkey FOREIGN KEY (translation_word_id) REFERENCES public.words(id) ON DELETE CASCADE;


--
-- Name: word_translations translations_word_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.word_translations
    ADD CONSTRAINT translations_word_id_fkey FOREIGN KEY (word_id) REFERENCES public.words(id) ON DELETE CASCADE;


--
-- Name: user_languages user_languages_base_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_languages
    ADD CONSTRAINT user_languages_base_language_id_fkey FOREIGN KEY (native_language_id) REFERENCES public.languages(id) ON DELETE RESTRICT;


--
-- Name: user_languages user_languages_learning_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_languages
    ADD CONSTRAINT user_languages_learning_language_id_fkey FOREIGN KEY (learning_language_id) REFERENCES public.languages(id) ON DELETE RESTRICT;


--
-- Name: user_languages user_languages_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_languages
    ADD CONSTRAINT user_languages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: user_sentences user_sentences_sentence_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_sentences
    ADD CONSTRAINT user_sentences_sentence_id_fkey FOREIGN KEY (sentence_id) REFERENCES public.sentences(id) ON DELETE CASCADE;


--
-- Name: user_sentences user_sentences_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_sentences
    ADD CONSTRAINT user_sentences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: user_vocabulary user_vocabulary_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_vocabulary
    ADD CONSTRAINT user_vocabulary_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: user_vocabulary user_vocabulary_word_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.user_vocabulary
    ADD CONSTRAINT user_vocabulary_word_id_fkey FOREIGN KEY (word_id) REFERENCES public.words(id) ON DELETE CASCADE;


--
-- Name: words words_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.words
    ADD CONSTRAINT words_language_id_fkey FOREIGN KEY (language_id) REFERENCES public.languages(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


