-- English alphabet (a-z). Vowels: a, e, i, o, u.
INSERT INTO letters (letter_sign, type, language_id) VALUES
('a', 'vowel', 1),
('b', 'consonant', 1),
('c', 'consonant', 1),
('d', 'consonant', 1),
('e', 'vowel', 1),
('f', 'consonant', 1),
('g', 'consonant', 1),
('h', 'consonant', 1),
('i', 'vowel', 1),
('j', 'consonant', 1),
('k', 'consonant', 1),
('l', 'consonant', 1),
('m', 'consonant', 1),
('n', 'consonant', 1),
('o', 'vowel', 1),
('p', 'consonant', 1),
('q', 'consonant', 1),
('r', 'consonant', 1),
('s', 'consonant', 1),
('t', 'consonant', 1),
('u', 'vowel', 1),
('v', 'consonant', 1),
('w', 'consonant', 1),
('x', 'consonant', 1),
('y', 'consonant', 1),
('z', 'consonant', 1);
