-- Migration 001: refresh token rotation with reuse detection and multi-device sessions.
--
-- Replaces the single plaintext users.refresh_token column (one session per
-- user, no rotation) with a refresh_tokens table: one row per issued token,
-- chained by family_id across rotations. expires_at is set once at family
-- creation and copied forward unchanged on every rotation, so it acts as an
-- absolute cap regardless of activity. A reused (already-rotated-away) token
-- revokes the whole family.
--
-- Idempotent: safe to re-run.
--
-- IMPORTANT deployment ordering: run this migration BEFORE deploying backend
-- code that depends on it. There is no data migration from the old
-- users.refresh_token column -- all currently logged-in users will need to
-- log in again the next time their access token expires (see rollout notes
-- in the implementation plan).

BEGIN;

CREATE TABLE IF NOT EXISTS public.refresh_tokens (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    family_id       uuid NOT NULL DEFAULT gen_random_uuid(),
    token_hash      text NOT NULL,
    created_at      timestamp with time zone NOT NULL DEFAULT now(),
    expires_at      timestamp with time zone NOT NULL,
    revoked_at      timestamp with time zone,
    replaced_by_id  bigint REFERENCES public.refresh_tokens(id) ON DELETE SET NULL,
    user_agent      text,
    ip_address      text,
    last_used_at    timestamp with time zone,
    CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash)
);

COMMENT ON TABLE public.refresh_tokens IS 'Refresh token sessions. One row per issued token; rotation chains rows via family_id. expires_at is fixed at family creation (absolute cap) and copied forward on rotation.';
COMMENT ON COLUMN public.refresh_tokens.family_id IS 'Shared by every token in a rotation chain from one login. Revoking a family revokes the whole chain (reuse detection / logout).';
COMMENT ON COLUMN public.refresh_tokens.expires_at IS 'Absolute cap set once at family creation; unchanged by rotation.';
COMMENT ON COLUMN public.refresh_tokens.revoked_at IS 'NULL = active. Set on rotation (old row), reuse detection, logout, or password reset.';

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_family_id ON public.refresh_tokens (family_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_active ON public.refresh_tokens (user_id) WHERE revoked_at IS NULL;

-- The old trigger/function bumped users.last_login whenever refresh_token
-- was set. That column is going away; the same behavior is now handled
-- explicitly in application code (usersModel.touchLastLogin), called only
-- on real login/register -- never on silent token refresh.
DROP TRIGGER IF EXISTS trigger_update_last_login ON public.users;
DROP FUNCTION IF EXISTS public.update_last_login_on_refresh_token();

ALTER TABLE public.users DROP COLUMN IF EXISTS refresh_token;

COMMIT;
