-- Migration 002: user feedback submissions.
--
-- Backs the public (no-auth) Feedback page served at
-- backend/public/feedback.html, linked from the app's More menu. Anyone can
-- submit without an account, so there's no user_id FK -- email is optional
-- and freely typed by the submitter.
--
-- Idempotent: safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS public.feedback (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category    text NOT NULL DEFAULT 'other',
    message     text NOT NULL,
    email       character varying(255),
    user_agent  text,
    ip_address  text,
    created_at  timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT feedback_category_check CHECK (category IN ('bug', 'suggestion', 'question', 'other')),
    CONSTRAINT feedback_message_not_blank CHECK (length(btrim(message)) > 0)
);

COMMENT ON TABLE public.feedback IS 'Feedback submitted via the public feedback page (backend/public/feedback.html), no account required.';

CREATE INDEX IF NOT EXISTS idx_feedback_created_at ON public.feedback (created_at DESC);

COMMIT;
