-- Migration 004: user_sentences - per-user saved-sentence progress, mirroring
-- user_vocabulary but for the sentences table. No level/proficiency column
-- exists on sentences, so unlike user_vocabulary there is no bulk
-- auto-seed path - rows are only ever created by explicit user action
-- (Save sentence in reels), never at registration/language-add time.
--
-- Idempotent: safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS public.user_sentences (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            bigint NOT NULL,
    sentence_id        bigint NOT NULL,
    user_languages_id  bigint NOT NULL,
    mastery_level      smallint NOT NULL DEFAULT 1,
    last_review        timestamp with time zone NOT NULL DEFAULT now(),
    created_at         timestamp with time zone NOT NULL DEFAULT now(),
    review_count       integer NOT NULL DEFAULT 0,
    next_review_at     timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_sentences_mastery_level_check CHECK (mastery_level >= 1 AND mastery_level <= 6),
    CONSTRAINT user_sentences_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT user_sentences_sentence_id_fkey FOREIGN KEY (sentence_id)
        REFERENCES public.sentences(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_sentences_user_languages FOREIGN KEY (user_languages_id)
        REFERENCES public.user_languages(id) ON DELETE CASCADE
);

COMMENT ON TABLE public.user_sentences IS 'Per-user saved sentences with mastery/review tracking, mirroring user_vocabulary. Populated only by explicit user action - no proficiency-based auto-seed, since sentences has no level column.';

-- (user_id, user_languages_id) backs get()'s scoped lookup, mirroring the
-- access pattern userVocabularyModel already relies on.
CREATE INDEX IF NOT EXISTS idx_user_sentences_user_lang ON public.user_sentences (user_id, user_languages_id);

-- No equivalent constraint exists on user_vocabulary (word_id), but the
-- "save sentence" UI action is a single fire-and-forget tap with no
-- already-saved check server-side, so this guards against a double-tap or a
-- stale-state race inserting a duplicate row. Paired with
-- ON CONFLICT DO NOTHING in userSentencesModel.add().
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_sentences_user_sentence ON public.user_sentences (user_id, sentence_id);

COMMIT;
